import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Icon } from './Icon';

interface ResultViewProps {
  title: string;
  content: string;
  onBack: () => void;
  onRetry: () => void;
  onNextStep?: () => void;
}

export const ResultView: React.FC<ResultViewProps> = ({ title, content, onBack, onRetry, onNextStep }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 md:py-12">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <button 
          onClick={onBack}
          className="flex items-center text-gray-500 hover:text-emerald-600 transition-colors group"
        >
          <Icon name="ArrowLeft" className="mr-2 group-hover:-translate-x-1 transition-transform" size={20} />
          {onNextStep ? 'Back to Step' : 'Back to Dashboard'}
        </button>

        <div className="flex space-x-3">
          <button 
            onClick={onRetry}
            className="flex items-center text-emerald-600 font-semibold hover:text-emerald-700 bg-emerald-50 px-4 py-2 rounded-lg transition-colors border border-emerald-100"
          >
            <Icon name="RefreshCw" className="mr-2" size={18} />
            Refine
          </button>
          
          {onNextStep && (
            <button 
              onClick={onNextStep}
              className="flex items-center text-white font-bold bg-gray-900 hover:bg-black px-6 py-2 rounded-lg transition-colors shadow-lg hover:shadow-xl"
            >
              Next Step
              <Icon name="ArrowRight" className="ml-2" size={18} />
            </button>
          )}
        </div>
      </div>

      <div className="bg-white rounded-3xl shadow-xl border border-gray-100 overflow-hidden">
        <div className="bg-gray-900 p-8 text-white border-b border-gray-800">
          <div className="flex items-center space-x-3">
            <Icon name="Sparkles" className="text-emerald-400" />
            <h2 className="text-2xl font-bold">AI Strategy: {title}</h2>
          </div>
        </div>
        
        <div className="p-8 md:p-12 prose prose-emerald max-w-none">
          <ReactMarkdown
             remarkPlugins={[remarkGfm]}
             components={{
              h1: ({node, ...props}) => <h1 className="text-3xl font-bold text-gray-900 mb-6 pb-2 border-b border-gray-100" {...props} />,
              h2: ({node, ...props}) => <h2 className="text-2xl font-bold text-gray-800 mt-8 mb-4" {...props} />,
              h3: ({node, ...props}) => <h3 className="text-xl font-bold text-gray-800 mt-6 mb-3" {...props} />,
              ul: ({node, ...props}) => <ul className="list-disc pl-6 space-y-2 mb-6 text-gray-700" {...props} />,
              ol: ({node, ...props}) => <ol className="list-decimal pl-6 space-y-2 mb-6 text-gray-700" {...props} />,
              li: ({node, ...props}) => <li className="pl-1" {...props} />,
              p: ({node, ...props}) => <p className="mb-4 text-gray-700 leading-relaxed" {...props} />,
              strong: ({node, ...props}) => <strong className="font-bold text-emerald-800" {...props} />,
              table: ({node, ...props}) => <div className="overflow-x-auto my-6"><table className="min-w-full divide-y divide-gray-200 border border-gray-200 rounded-lg" {...props} /></div>,
              th: ({node, ...props}) => <th className="bg-gray-50 px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider" {...props} />,
              td: ({node, ...props}) => <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600 border-t border-gray-100" {...props} />,
            }}
          >
            {content}
          </ReactMarkdown>
        </div>
        
        <div className="bg-gray-50 p-6 text-center text-gray-500 text-sm border-t border-gray-100">
           Generated by Gemini 3 Pro Preview. Results may vary. Always verify project critical data.
        </div>
      </div>
    </div>
  );
};